spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: 3xp3r13nc3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      add-mappings: false
